# Basic Matrix Operations

### Matrix Addition

Let $A=[a_{ij}]$ and $B=[b_{ij}]$ be two matrices of dimensions $m \times n$. Then the sum of matrices $A$ and $B$ is the matrix $C=[c_{ij}]$ of dimensions $m \times n$, where $c_{ij}=a_{ij}+b_{ij}$.

### Matrix Scalar Multiplication

Let $A=[a_{ij}]$ be a matrix of dimensions $m \times n$, and let $k$ be a scalar. Then the product of matrix $A$ and scalar $k$ is the matrix $B=[b_{ij}]$ of dimensions $m \times n$, where $b_{ij}=k \cdot a_{ij}$.

### Matrix Multiplication

Let $A=[a_{ij}]$ be a matrix of dimensions $m \times n$, and $B=[b_{ij}]$ be a matrix of dimensions $n \times p$. Then the product of matrices $A$ and $B$ is the matrix $C=[c_{ij}]$ of dimensions $m \times p$, where $c_{ij}=\sum_{k=1}^{n} a_{ik} \cdot b_{kj}$.


### Example 1

Let $A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ and $B=\begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$.
Then the sum of matrices $A$ and $B$ is

$$
C=
A+B=\begin{bmatrix} 1+5 & 2+6 \\ 3+7 & 4+8 \end{bmatrix}=\begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix}.
$$

### Example 2

Let $A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ and $k=2$.

Then the product of matrix $A$ and scalar $k$ is

$$
B=
k \cdot A=2 \cdot \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}=\begin{bmatrix} 2*1 & 2*2 \\ 2*3 & 2*4 \end{bmatrix}=\begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix}.
$$

### Example 3

Let
$A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$
and
$B=\begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$.

Then the product of matrices $A$ and $B$ is

$$
C=
A \cdot B=\begin{bmatrix} 1*5+2*7 & 1*6+2*8 \\ 3*5+4*7 & 3*6+4*8 \end{bmatrix}=\begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}.
$$

In [ ]:
# Example 1: Matrix addition in sympy
import sympy as sp

A=sp.Matrix([[1,2],[3,4]])
B=sp.Matrix([[5,6],[7,8]])
A # display matrix A

In [ ]:
B # display matrix B

In [ ]:
sp.Matrix([[6,8],[10,12]])==A+B # verify matrix addition

In [ ]:
# Example 2: Scalar multiplication
A=sp.Matrix([[1,2],[3,4]]) # define matrix A

sp.Matrix([[2,4],[6,8]])==2*A # verify scalar multiplication

In [ ]:
# Example 3: Multiplication of two matrices

A=sp.Matrix([[1,2],[3,4]]) # define matrix A
B=sp.Matrix([[5,6],[7,8]]) # define matrix B

sp.Matrix([[19,22],[43,50]])==A*B # verify matrix multiplication

### Necessary Condition for Matrix Multiplication

Remember that matrices can have different numbers of rows and columns.

To multiply two matrices $A_{m \times n}$ and $B_{n \times k}$, where $A$ has dimensions $m \times n$ and $B$ has dimensions $n \times k$, the number of columns of matrix $A$ must equal the number of rows of matrix $B$. Otherwise, matrix multiplication is not possible.

$$
A_{m \times n} \cdot B_{n \times k} = C_{m \times k}
$$

For example, if $A_{3 \times 3}$ and $B_{3 \times 3}$, then the resulting matrix $C_{3 \times 3}$.

<img src="https://www.mscroggs.co.uk/img/full/multiply_matrices.gif" alt="Matrix Multiplication GIF" width="400">

### Matrix Multiplication is Not Commutative

Matrix multiplication is not commutative, i.e., in general $A \cdot B \neq B \cdot A$.

In [ ]:
# Example of multiplying rectangular matrices
import sympy as sp
A=sp.Matrix([[1,2],[3,4],[5,6]]) # define matrix A_{3 x 2}
B=sp.Matrix([[1,2,3],[4,5,6]]) # define matrix B_{2 x 3}
C=sp.Matrix([[9,12,15],[19,26,33],[29,40,51]]) # define matrix C_{3 x 3}

A*B # multiply matrices A and B to get a 3x3 matrix

In [ ]:
B*A # multiply matrices B and A to get a 2x2 matrix

In [3]:
B*C # multiply matrices B and C to get a 2x3 matrix

array([[-5, 12],
       [21,  0]])

In [2]:
import numpy as np

# Define the matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[-1, 2], [3, 0]])
D = np.array([[-1, 2, 3], [4, 0, 6]])
E = np.array([[1, 2], [4, 5], [7, 8]])

# 1. Matrix addition and subtraction
A_plus_B = A + B
B_minus_A = B - A

# A + C can be calculated (same dimensions)
A_plus_C = A + C

# D + E cannot be calculated (different dimensions), handle separately
try:
    D_plus_E = D + E
except ValueError:
    D_plus_E = "Not defined (dimensions mismatch)"

# 2. Scalar multiplications
half_A = 0.5 * A
two_B = 2 * B
neg_three_C = -3 * C
four_D = 4 * D

# 3. Matrix multiplications
A_dot_B = np.dot(A, B)
try:
    A_dot_D = np.dot(A, D)  # Multiplication only if inner dimensions match
except ValueError:
    A_dot_D = "Not defined (dimensions mismatch)"

try:
    D_dot_E = np.dot(D, E)
except ValueError:
    D_dot_E = "Not defined (dimensions mismatch)"

# Print all results
print("1. Matrix Addition and Subtraction:")
print("A + B:\n", A_plus_B)
print("B - A:\n", B_minus_A)
print("A + C:\n", A_plus_C)
print("D + E:\n", D_plus_E)

print("\n2. Scalar Multiplications:")
print("0.5A:\n", half_A)
print("2B:\n", two_B)
print("-3C:\n", neg_three_C)
print("4D:\n", four_D)

print("\n3. Matrix Multiplications:")
print("A · B:\n", A_dot_B)
print("A · D:\n", A_dot_D)
print("D · E:\n", D_dot_E)



1. Matrix Addition and Subtraction:
A + B:
 [[ 6  8]
 [10 12]]
B - A:
 [[4 4]
 [4 4]]
A + C:
 [[0 4]
 [6 4]]
D + E:
 Not defined (dimensions mismatch)

2. Scalar Multiplications:
0.5A:
 [[0.5 1. ]
 [1.5 2. ]]
2B:
 [[10 12]
 [14 16]]
-3C:
 [[ 3 -6]
 [-9  0]]
4D:
 [[-4  8 12]
 [16  0 24]]

3. Matrix Multiplications:
A · B:
 [[19 22]
 [43 50]]
A · D:
 [[ 7  2 15]
 [13  6 33]]
D · E:
 [[28 32]
 [46 56]]


---
## Exercises for Students (old version)

1. Calculate the sum of matrices $A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ and $B=\begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$.

2. Calculate the product of matrix $A=\begin{bmatrix} 4 & 2 \\ 12 & 4 \end{bmatrix}$ and scalar $k=\frac{1}{4}$.

3. Calculate the products $A\cdot B$ and $B \cdot A$ for matrices $A=\begin{bmatrix} 3 & 2 \\ 2 & 4 \end{bmatrix}$ and $B=\begin{bmatrix} 4 & 1 \\ 6 & 4 \end{bmatrix}$.


## Exercises for Students (new version)

For follwing matrices

$$
\mathbf{A}=
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\qquad
\mathbf{B}=
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
\quad
\mathbf{C}=
\begin{pmatrix}
-1 & 2 \\
3 & 0
\end{pmatrix}
\qquad
\mathbf{D}=
\begin{pmatrix}
-1 & 2 & 3 \\
4 & 0 & 6
\end{pmatrix}
\qquad
\mathbf{E}=
\begin{pmatrix}
1 & 2\\
4 & 5\\
7 & 8
\end{pmatrix}
$$

1. Calculate: $\mathbf{A}+\mathbf{B}$;  $\mathbf{B}-\mathbf{A}$;  $\mathbf{A}+\mathbf{C}$; $\mathbf{D}+\mathbf{E}$.

2. Calculate $\frac{1}{2}\mathbf{A}$, $2\mathbf{B}$, $-3\mathbf{C}$, and $4\mathbf{D}$.

3. Calculate the products $\mathbf{A}\cdot \mathbf{B}$; $\mathbf{B} \cdot \mathbf{A}$; $\mathbf{A} \cdot \mathbf{D}$; $\mathbf{D} \cdot \mathbf{E}$.