# Determinants of 2x2 and 3x3 matrices

### Determinant of a 2x2 Matrix

The general formula for the determinant of a 2x2 matrix, where the matrix looks as follows:

$$
\mathbf{A} =
\begin{pmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{pmatrix}
$$

The determinant of a 2x2 matrix is calculated using the formula:

$$
\text{det}(A) = a_{11} \cdot a_{22} - a_{12} \cdot a_{21}
$$

### Determinant of a 3x3 Matrix

The general formula for the determinant of a 3x3 matrix, where the matrix looks as follows:

$$
\mathbf{B} =
\begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{pmatrix}
$$

The determinant of a 3x3 matrix can be calculated using Sarrus' rule or Laplace expansion. Here, we will use Sarrus' rule:

$$
\text{det}(B) = a_{11} \cdot a_{22} \cdot a_{33} + a_{12} \cdot a_{23} \cdot a_{31} + a_{13} \cdot a_{21} \cdot a_{32}
- a_{13} \cdot a_{22} \cdot a_{31} - a_{12} \cdot a_{21} \cdot a_{33} - a_{11} \cdot a_{23} \cdot a_{32}
$$

<img src="https://upload.wikimedia.org/wikipedia/commons/c/c0/Sarrus_rule1.svg" alt="Image description" width="300" align="center"/>

Note: Sarrus' rule does not work for matrices larger than 3x3.

### Calculating Determinants in Python using SymPy

Now, using the SymPy library, we will calculate the determinants for 2x2 and 3x3 matrices.

In [ ]:
import sympy as sp

# Define the matrix
A = sp.Matrix([[2, 3], [1, 4]])
A # display the matrix

Matrix([
[2, 3],
[1, 4]])

In [ ]:
# Verify the correctness of the calculations
(2*4 - 3*1) == A.det()

True

In [ ]:
# 3x3 Matrix
B = sp.Matrix([[2, 3, 1], [1, 4, 5], [3, 2, 1]])
B

Matrix([
[2, 3, 1],
[1, 4, 5],
[3, 2, 1]])

In [ ]:
# Verify the correctness of the calculations
(2*4*1 + 3*5*3 + 1*1*2 - 1*4*3 - 5*2*2 - 3*1*1) == B.det()

True

In [ ]:
import numpy as np

# Define the updated 2x2 matrices
A = np.array([[2, 3], [1, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[-1, 2], [3, 0]])

# Calculate the determinants
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)

# Print the results
print("Determinant of matrix A:", det_A)
print("Determinant of matrix B:", det_B)
print("Determinant of matrix C:", det_C)


In [1]:
import numpy as np

# Define the matrices
D = np.array([[1, 0, 2],
              [-1, 3, 1],
              [2, -2, 4]])

E = np.array([[3, 1, -1],
              [0, 2, 4],
              [5, 3, 2]])

F = np.array([[2, -3, 1],
              [1, 4, -2],
              [1, 5, 3]])

# Matrix addition
sum_DE = D + E

# Matrix multiplication
product_DE = np.dot(D, E)

# Matrix transpose
transpose_D = D.T

# Print the results
print("D + E:\n", sum_DE)
print("\nD * E:\n", product_DE)
print("\nTranspose of D:\n", transpose_D)



D + E:
 [[ 4  1  1]
 [-1  5  5]
 [ 7  1  6]]

D * E:
 [[13  7  3]
 [ 2  8 15]
 [26 10 -2]]

Transpose of D:
 [[ 1 -1  2]
 [ 0  3 -2]
 [ 2  1  4]]


---

## Exercises for Students

Calculate the determinants for the 2x2 and 3x3 matrices given below.

1. 2x2 Matrices:

$$
\mathbf{A} =
\begin{pmatrix}
2 & 3 \\
1 & 4
\end{pmatrix}
, \qquad
\mathbf{B} =
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
, \qquad
\mathbf{C} =
\begin{pmatrix}
-1 & 2 \\
3 & 0
\end{pmatrix}
$$

2. 3x3 Matrices:


$$
\mathbf{D} =
\begin{pmatrix}
1 & 0 & 2 \\
-1 & 3 & 1 \\
2 & 4 & -2
\end{pmatrix}
, \qquad
\mathbf{E} =
\begin{pmatrix}
3 & 1 & -1 \\
0 & 2 & 4 \\
5 & 3 & 2
\end{pmatrix}
, \qquad
\mathbf{F} =
\begin{pmatrix}
2 & -3 & 1 \\
1 & 4 & -2 \\
1 & 5 & 3
\end{pmatrix}
$$